default_platform(:ios)

platform :ios do
  lane :ci do
    scan(
      project: "CICDDemoApp.xcodeproj
      scheme: "CICDDemoApp",
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.5"
    )
  end
end
