name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Matches the Ruby version in your logs
          bundler-cache: false # We will handle bundler manually to avoid version conflicts

      - name: Install Bundler 2.x
        run: gem install bundler:2.5.11

      - name: Install Dependencies
        run: bundle _2.5.11_ install
        working-directory: CICDDemoApp

      - name: Run Fastlane
        run: fastlane ci
        working-directory: CICDDemoApp
